### ISSUE TITLE
[자료구조] 재귀 알고리즘의 장점과 단점에 대해서 설명해보세요

### ISSUE THREAD

**Issue by sw0501** [SSAFY-10-ALGORITHM-STUDY/Algorithm-Study#1]

**Comment by sw0501** [comment]
하노이탑 문제 해결에 사용됩니다.,

**Comment by sw0501** [comment]
[재귀] 재귀 알고리즘이 활용되는 예시
실무에서 거의 쓰이지 않기 때문에 다른 질문으로 변경했습니다.

**Comment by sw0501** [comment]
장점
- 코드가 간결해진다. 
- 반복문에 비해 변수를 덜 사용한다. 
단점
- 지역 변수, 매개 변수, 반환값을 모두 스택에 저장하여 반복문에 비해 더 많은 메모리를 사용한다.   
- 함수를 반복적으로 호출 및 리턴하기 때문에 컨텍스트 스위칭 비용이 계속해서 발생한다.

**Comment by PARKSEGUN** [comment]
# 장점
- 변수의 개수를 줄일 수 있다 -> 작동되는 상태를 변수에 작동되기 때문에 모든 경우의 상태를 저장시키는 것을 방지
- 코드의 가독성 증가
# 단점
- 메서드가 스택에 쌓이기 때문에 너무 커진다면 비효율적인 속도가 된다.'
- 시간 복잡도 계산이 어렵다.
