### ISSUE TITLE
[자료구조] 재귀 알고리즘에 대해 설명하세요

### ISSUE THREAD

**Issue by sw0501** [SSAFY-10-ALGORITHM-STUDY/Algorithm-Study#2]

**Comment by sw0501** [comment]
재귀 알고리즘이란 함수가 자신을 반복적으로 호출하면서 동작하도록 구현한 알고리즘입니다.
자신을 반복적으로 호출하기 때문에 반드시 종료 조건이 필요합니다.

**Comment by PARKSEGUN** [comment]
- 분할정복의 한 유형으로 문제를 쪼개서 연산을 분산시킨다
- 반복문의 중첩과 복잡성을 해결하기위해
- 자기 자신을 부르는 재귀함수를 사용
- 재귀함수가 스택에 쌓이면서 작동
