### ISSUE TITLE
[네트워크] Http와 Https를 비교해 주세요.

### ISSUE THREAD

**Issue by daunjeong824** [SSAFY-10-ALGORITHM-STUDY/Algorithm-Study#4]

**Comment by daunjeong824** [comment]
http는 서로 다른 어플리케이션 간 기본 통신 프로토콜, 암호화 처리가 되어있지 않는다.

https는 http에 데이터 암호화가 추가된 프로토콜, SSL 인증서를 활용하여, 네트워크 상에서 3자가 정보를 확인할 수 없도록 암호화하여 전송한다.

**Comment by sw0501** [comment]
HTTP: 어플리케이션간 기본 통신 프로토콜로 암호화되어 있지 않음
HTTPS: HTTP에 암호화가 추가된 방식의 프로토콜로 SSL 인증을 통해 외부에서 데이터를 탈취해도 
해당 내용을 복호화할 수 없어 데이터의 안정성을 보장한다.
